# Generated by Django 5.2 on 2025-05-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='thumb_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
